version: '3'
services:
    app:
        build: .
        ports:
            - '5577:5577'
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - '27017:27017'
